### ISSUE TITLE
Use HyTTP module to work with HTTP requests and responses

### ISSUE THREAD

**Issue by dankkomcg** [dankkomcg/stitch#3]
# Task to use HyTTP

* [x] Install composer package `composer require dankkomcg\hyttp`.
* [x] Create a cable class between router and request to use `RexPI` to search the correct URL work.
* [x] Connect `StitchAPI` with `Router` and `HyTTP` to pass correct values to `Server`.
* [x] Test it.
